backendHostname: ''
backendIP: 192.168.60.2
backendLanguage: ''
backendPort: 5558
dbMode: mssql
parserIP: ''
parserPort: ''
parserToken: ''
sqlDatabase: ''
sqlPassword: ''
sqlServerIP: ''
sqlUsername: ''
useSSL: false
