backendHostname: receiptmanager.home.local
backendIP: 192.168.60.2
backendLanguage: de-DE
backendPort: 5558
dbMode: mssql
encrypted: true
parserIP: 192.168.50.6
parserPort: 8721
parserToken: 96fd470a0df21d7aa10a951229840dc6
sqlDatabase: receiptData
sqlPassword: 80dd4f361dfa0e5b9630b4060db63df4819919f13ccad93e4b9b6282c7f14c70
sqlServerIP: 192.168.50.6
sqlUsername: receiptParser
useSSL: false
