backendHostname: ''
backendIP: 192.168.60.2
backendLanguage: de-DE
backendPort: 5558
dbMode: mssql
parserIP: ''
parserPort: ''
parserToken: ''
sqlDatabase: ''
sqlPassword: Test
sqlServerIP: ''
sqlUsername: ''
useSSL: false
